SELECT DISTINCT * WHERE {
?x <http://www.w3.org/2004/02/skos/core#subject> <http://dbpedia.org/resource/Category:FIFA_World_Cup-winning_countries> .
?p <http://dbpedia.org/ontology/managerClub> ?x .
?p <http://xmlns.com/foaf/0.1/name> "Luiz Felipe Scolari"@en .
}
